# Generated by Django 5.1.3 on 2025-01-05 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('deptno', models.IntegerField(max_length=50, primary_key=True, serialize=False)),
                ('deptname', models.CharField(max_length=100)),
                ('deptloc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('empid', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=30)),
                ('empjob', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empsal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empcomm', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('emphirdate', models.DateField()),
                ('deptno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
                ('empmgr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.emp')),
            ],
        ),
    ]
